server:
  port: 9999
  context-path: /uaa
  
security:
  user:
    password: password
    
    
logging:
  level:
    org:
      springframework:
        security: DEBUG
        
#endpoints:
#  cors:
#    allowed-origins: "*"
#    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
#    allowed-headers: "*"
#    exposed-headers:
#    allow-credentials: true
#    max-age: 1800
    


spring:  
  datasource:  
    url : jdbc:mysql://localhost:3306/uaa  
    username : root  
    password : Huawei12#$  
    driverClassName : com.mysql.jdbc.Driver  
  jpa:  
    database : MYSQL  
    show-sql : true  
    hibernate:  
      ddl-auto : update  
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy  
    properties:  
      hibernate:  
        dialect : org.hibernate.dialect.MySQL5Dialect  