server:
  port: 9999
  context-path: /uaa
  
security:
  user:
    password: password
    
    
logging:
  level:
    org:
      springframework:
        security: DEBUG
        
endpoints:
  cors:
    allowed-origins: "*"
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: "*"
    exposed-headers:
    allow-credentials: true
    max-age: 1800